name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images for each service
      - name: Build and push API Gateway image
        run: |
          docker build -t kathanprajapati/apigateway_image ./api_gateway
          docker push kathanprajapati/apigateway_image

      - name: Build and push User Service v1 image
        run: |
          docker build -t kathanprajapati/user_v1_image ./user_service_v1
          docker push kathanprajapati/user_v1_image

      - name: Build and push User Service v2 image
        run: |
          docker build -t kathanprajapati/user_v2_image ./user_service_v2
          docker push kathanprajapati/user_v2_image

      - name: Build and push Order Service image
        run: |
          docker build -t kathanprajapati/order_service_image ./order_service
          docker push kathanprajapati/order_service_image

      - name: Build and push Event System image
        run: |
          docker build -t kathanprajapati/event_system_image ./event_system
          docker push kathanprajapati/event_system_image

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull kathanprajapati/apigateway_image && docker run -d --name apigateway_container -p 5000:5000 kathanprajapati/apigateway_image"
          
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull kathanprajapati/user_v1_image && docker run -d --name user_v1_container -p 5001:5001 kathanprajapati/user_v1_image"
          
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull kathanprajapati/user_v2_image && docker run -d --name user_v2_container -p 5002:5002 kathanprajapati/user_v2_image"
          
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull kathanprajapati/order_service_image && docker run -d --name order_service_container -p 5003:5003 kathanprajapati/order_service_image"
          
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "docker pull kathanprajapati/event_system_image && docker run -d --name event_system_container -p 5004:5004 kathanprajapati/event_system_image"

